name: elderhaven
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  sqflite: ^2.0.0+4
  pdf: ^3.8.0
  path_provider: ^2.0.9
  url_launcher: ^6.0.17
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  charts_flutter: ^0.12.0 # Ensure this is included
  image_picker: ^1.1.2  # Update to the latest version
  http: ^1.2.0 # Update to the latest version
  intl: ^0.17.0
  health: ^3.0.6
  flutter_blue: ^0.8.0
  shared_preferences: ^2.0.10
  google_sign_in: ^6.0.0
  flutter_facebook_auth: ^7.1.1
  fluttertoast: ^8.2.1
  geolocator: ^13.0.1
  flutter_dotenv: ^5.0.2
  location: ^4.4.0
  flutter_sms: ^2.3.2
  permission_handler: ^10.0.0
  google_generative_ai: ^0.4.6
  provider: ^6.0.0
  uuid: ^4.0.0
  flutter_secure_storage: ^9.2.2
  in_app_purchase: ^3.0.7
  upi_pay: ^1.0.1
  qr_flutter: ^4.1.0
  flutter_webrtc: ^0.6.10
  xml: ^6.5.0
  webview_flutter: ^4.0.1
  html: ^0.15.0
  cloud_firestore: ^3.5.1




  flutter_bloc: ^8.0.0
  contacts_service: ^0.6.3
  firebase_auth: ^3.1.6  # Optional, for user authentication (optional)
  firebase_core: ^1.13.0
  jitsi_meet_wrapper: ^0.2.0+1
  geofence_service: ^6.0.0+1
  flutter_background_geolocation: ^4.11.0
  math_expressions: ^2.6.0
  table_calendar: ^3.0.8
  flutter_blue_plus: ^1.34.5
  flutter_blue_plus_windows: ^1.26.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/default.png
    - assets/underweight.png
    - assets/normal.png
    - assets/overweight.png
    - assets/obese.png
    - assets/feature_image.png
    - assets/medical_image.png
    - assets/game.png
    - assets/doctor_image.png
