// File: health_problem_details_screen.dart

import 'package:flutter/material.dart';

class HealthProblemDetailsScreen extends StatelessWidget {
  final String problem;

  HealthProblemDetailsScreen({required this.problem});

  // Sample data for details (this can be retrieved from an API or database later)
  final Map<String, String> problemDetails = {
    'Diabetes': 'A chronic condition that affects the way the body processes blood sugar (glucose). '
        'Diabetes is a chronic medical condition characterized by elevated blood sugar (glucose) levels due to insufficient insulin production or poor cellular response to insulin. There are three primary types: Type 1 diabetes, an autoimmune condition where the body fails to produce insulin; Type 2 diabetes, which typically develops due to insulin resistance and is often linked to obesity and lifestyle factors; and gestational diabetes, which occurs during pregnancy. Common symptoms include excessive thirst, frequent urination, fatigue, and blurred vision. If left untreated, diabetes can lead to serious complications, including heart disease, kidney failure, nerve damage, and vision problems. Effective management includes lifestyle changes, regular monitoring, and medication or insulin therapy as needed.The symptoms of diabetes can vary based on the type and severity of the condition. Common symptoms include increased thirst (polydipsia), frequent urination (polyuria), and extreme hunger (polyphagia), which arise due to the body’s inability to utilize glucose effectively. Individuals may also experience fatigue, blurred vision, and slow healing of wounds, as high blood sugar levels can impair circulation and healing processes. Other symptoms can include tingling or numbness in the hands and feet, dark patches of skin (acanthosis nigricans) in body folds, and unexplained weight loss, especially in Type 1 diabetes. Additionally, people with diabetes may have a higher susceptibility to infections. If these symptoms are present, it’s important to consult a healthcare professional for proper evaluation and diagnosis.',
    'Hypertension': 'A condition in which the force of the blood against the artery walls is too high.'
        'Hypertension, commonly known as high blood pressure, is a medical condition where the force of the blood against the walls of the arteries is consistently too high. Blood pressure is measured in millimeters of mercury (mm Hg) and is expressed as two numbers: systolic pressure (the pressure in the arteries when the heart beats) over diastolic pressure (the pressure in the arteries when the heart rests between beats). A normal blood pressure reading is typically around 120/80 mm Hg, while hypertension is generally defined as having readings of 130/80 mm Hg or higher. Hypertension often has no noticeable symptoms, which is why it is sometimes called the "silent killer." If left untreated, it can lead to serious health complications, including heart disease, stroke, kidney damage, and other cardiovascular problems. Managing hypertension typically involves lifestyle changes (such as diet and exercise) and may also include medication to help lower blood pressure.',
    'Arthritis': 'Inflammation of one or more of your joints, causing pain and stiffness. Arthritis is a general term that refers to a group of more than 100 different diseases and conditions characterized by inflammation of the joints. It can lead to pain, stiffness, swelling, and decreased range of motion in affected joints. Arthritis can affect people of all ages, genders, and ethnic backgrounds, but it is more common in older adults.Other types of arthritis include gout, psoriatic arthritis, and juvenile arthritis.Symptoms can vary widely depending on the type and severity of arthritis but often include joint pain, swelling, stiffness, and reduced mobility. Treatment typically involves a combination of medication, physical therapy, lifestyle changes, and, in some cases, surgery to manage symptoms and improve quality of life.The symptoms of arthritis can vary depending on the specific type and severity of the condition.',
    'Heart Disease': 'Conditions that involve narrowed or blocked blood vessels.Heart disease is a broad term that refers to various types of conditions that affect the heart structure and function. It encompasses a range of cardiovascular issues, including:Coronary Artery Disease (CAD)*: The most common type of heart disease, CAD occurs when the coronary arteries become narrowed or blocked due to a buildup of plaque (cholesterol, fat, and other substances). This can lead to chest pain (angina) or heart attacks.Heart Failure: A condition where the heart is unable to pump blood effectively, leading to a buildup of fluid in the lungs and other parts of the body. It can result from various underlying issues, including CAD and high blood pressure.Arrhythmias: These are irregular heartbeats that can be too fast, too slow, or erratic. Some arrhythmias are harmless, while others can be life-threatening.Heart Valve Problems: This includes conditions affecting the heart valves, which control blood flow through the heart. Problems may involve stenosis (narrowing) or regurgitation (leakage).Congenital Heart Defects: These are structural problems with the heart that are present at birth, affecting the heart’s walls, valves, or blood vessels.Peripheral Artery Disease (PAD)*: This condition occurs when the arteries that supply blood to the legs and arms become narrowed or blocked, reducing blood flow.',
    'Asthma': 'A condition in which your airways narrow and swell and may produce extra mucus.The symptoms of asthma can vary in severity and frequency among individuals but typically include wheezing, which is a whistling or squeaky sound when breathing, particularly during exhalation. Shortness of breath is also common, leading to difficulty breathing during physical exertion or at rest. Many people experience a feeling of chest tightness, often described as pressure or a band tightening around the chest. Coughing is another hallmark symptom, particularly at night or early in the morning, and it can worsen with respiratory infections or exposure to triggers. Additionally, individuals with asthma may produce excess mucus in the airways, contributing to coughing and breathing difficulties. Symptoms can disrupt sleep, leading to fatigue due to the increased effort to breathe and interrupted rest. Various factors can trigger asthma symptoms, including allergens, respiratory infections, physical activity, cold air, smoke, and strong odors. The severity of symptoms can range from mild to severe and may fluctuate over time. If worsening asthma symptoms occur or if breathing becomes difficult, it is essential to seek medical attention, as regular monitoring and management are crucial for controlling the condition and preventing severe asthma attacks',
    'Allergies': 'A condition in which the immune system reacts abnormally to a foreign substance.Allergies occur when the immune system reacts to a substance (allergen) that is usually harmless, such as pollen, dust mites, pet dander, certain foods, or insect stings. Common symptoms include sneezing, itching, hives, and difficulty breathing. Allergies can be managed through avoidance of triggers, antihistamines, and in some cases, allergy shots (immunotherapy) to desensitize the immune system. It essential for individuals with allergies to work with healthcare providers to develop effective management strategies',
    'Cholesterol': 'A waxy substance found in your blood. Too much can increase the risk of heart disease.Cholesterol is a waxy, fat-like substance found in every cell of the body, essential for producing hormones, vitamin D, and bile acids that help digest fat. It is transported in the bloodstream by lipoproteins, primarily low-density lipoprotein (LDL) and high-density lipoprotein (HDL).LDL cholesterol is often referred to as "bad" cholesterol because high levels can lead to plaque buildup in arteries, increasing the risk of heart disease and stroke.HDL cholesterol is known as "good" cholesterol because it helps remove LDL cholesterol from the bloodstream.Maintaining a healthy balance between these types is crucial for cardiovascular health. Lifestyle factors like diet, exercise, and avoiding tobacco can help manage cholesterol levels. In some cases, medication may be necessary to control high cholesterol. Regular check-ups and blood tests can help monitor cholesterol levels.',
    'Obesity': 'A condition involving excessive body fat that increases the risk of health problems.Obesity is a medical condition characterized by an excessive accumulation of body fat, which can negatively impact health. It is often measured using the Body Mass Index (BMI), a calculation based on height and weight. A BMI of 30 or higher is typically classified as obesity.Genetics: Family history can influence metabolism and fat storage. Diet: High-calorie diets, especially those rich in sugars and fats, contribute significantly to weight gain.Physical Inactivity: Sedentary lifestyles, including excessive screen time, lead to lower energy expenditure.Environment: Limited access to healthy foods and recreational spaces can increase obesity risk.Psychological Factors: Emotional stress, depression, and anxiety can lead to overeating or unhealthy eating habits.Obesity is associated with a range of health issues, including: Cardiovascular Diseases: Increased risk of heart disease and stroke.Type 2 Diabetes: Obesity is a major risk factor for developing insulin resistance.Certain Cancers: Increased risk of cancers such as breast, colon, and endometrial cancer.Joint Problems: Extra weight puts strain on joints, leading to conditions like osteoarthritis..Sleep Apnea: Obesity can lead to breathing problems during sleep.Management and Prevention.Dietary Changes: Adopting a balanced diet rich in fruits, vegetables, whole grains, and lean proteins while limiting processed foodsRegular Exercise: Engaging in physical activity for at least 150 minutes a week can help maintain a healthy weight.Behavioral Therapy: Counseling or support groups can help address emotional eating and establish healthier habits.Medical Intervention: In some cases, medications or bariatric surgery may be considered for severe obesity.of Awareness:Addressing obesity requires a comprehensive approach involving individuals, healthcare providers, and communities to promote healthier lifestyles and reduce stigma associated with weight. Regular health screenings can help monitor weight and related health risks.',
    'Depression': 'A condition in which bones become weak and brittle.Depression is a common and serious mental health disorder characterized by persistent feelings of sadness, loss of interest or pleasure in activities, and a range of emotional and physical problems. It can affect how a person thinks, feels, and handles daily activities.Symptoms:Symptoms of depression can vary widely but generally include:Persistent sadness or low mood Loss of interest or pleasure in activities once enjoyed Changes in appetite or weight (increased or decreased)Sleep disturbances (insomnia or excessive sleeping)Fatigue or low energe.Difficulty concentrating, making decisions, or remembering things Feelings of worthlessness or excessive guide.Thoughts of death or suicide.Causes:Depression can result from a combination of factors, including:Genetics: Family history of depression may increase the risk.Biochemical Factors: Neurotransmitter imbalances in the brain can affect mood regulation.Environmental Factors: Life events, trauma, or chronic stress can trigger depressive episodes.Psychological Factors: Low self-esteem, negative thinking patterns, and lack of coping skills can contribute.Types of Depression:Major Depressive Disorder: Characterized by severe symptoms that interfere with daily life.Persistent Depressive Disorder (Dysthymia): Chronic but less severe depression lasting for at least two years.Bipolar Disorder: Includes episodes of depression along with periods of mania or elevated mood.Seasonal Affective Disorder (SAD): Depressive episodes occurring at specific times of the year, usually in winter.Treatment:Treatment for depression often involves a combination of approaches',
    'Osteoporosis': 'A mood disorder that causes a persistent feeling of sadness and loss of interest.Depression is a common and serious mental health disorder characterized by persistent feelings of sadness, loss of interest or pleasure in activities, and a range of emotional and physical problems. It can affect how a person thinks, feels, and handles daily activities.Symptoms:Symptoms of depression can vary widely but generally include:Persistent sadness or low mood Loss of interest or pleasure in activities once enjoyed Changes in appetite or weight (increased or decreased)Sleep disturbances (insomnia or excessive sleeping)Fatigue or low energe.Difficulty concentrating, making decisions, or remembering things Feelings of worthlessness or excessive guil.Thoughts of death or suicide.Causes:Depression can result from a combination of factors, including:Genetics: Family history of depression may increase the risk.Biochemical Factors: Neurotransmitter imbalances in the brain can affect mood regulation.Environmental Factors: Life events, trauma, or chronic stress can trigger depressive episodes.Psychological Factors: Low self-esteem, negative thinking patterns, and lack of coping skills can contribute.Types of Depression:Major Depressive Disorder: Characterized by severe symptoms that interfere with daily life.Persistent Depressive Disorder (Dysthymia): Chronic but less severe depression lasting for at least two years.Bipolar Disorder: Includes episodes of depression along with periods of mania or elevated mood.Seasonal Affective Disorder (SAD): Depressive episodes occurring at specific times of the year, usually in winter.Treatment:Treatment for depression often involves a combination of approaches',
    'Migraine': 'A headache of varying intensity, often accompanied by nausea and sensitivity to light and sound.Migraine is a neurological condition characterized by recurrent, severe headaches often accompanied by other symptoms. Migraines can significantly impact daily life and are typically more intense than regular headaches.Symptoms:Headache: Usually unilateral (affecting one side of the head) and throbbing or pulsating in nature.Aura: Some individuals experience visual disturbances (flashes of light, blind spots) or sensory changes (tingling) before the headache.Nausea and Vomiting: Many people experience gastrointestinal symptoms during a migraine attack..Migraine With Aura: Accompanied by neurological symptoms before the headache begins.Chronic Migraine: Occurs 15 or more days per month for at least three months.Diagnosis:Migraine is diagnosed based on medical history, symptom patterns, and physical examination. Imaging tests may be conducted to rule out other causes of headaches.Treatment:Medications:Abortive Treatments: Triptans, NSAIDs, and other medications to relieve pain during an attack.Preventive Treatments: Daily medications (beta-blockers, antidepressants, anticonvulsants) to reduce the frequency and severity of migraines.Lifestyle ChangesKeeping a headache diary to identify triggers.Managing stress through relaxation techniques.Maintaining a regular sleep schedule.Alternative Therapies: Acupuncture, biofeedback, and herbal supplements may provide relief for some individuals.Importance of Management:Effective management of migraines is crucial for improving quality of life. Individuals experiencing frequent or severe migraines should consult healthcare professionals for personalized treatment strategies.',
  };

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(problem),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Text(
          problemDetails[problem] ?? 'Details not available.',
          style: TextStyle(fontSize: 18),
        ),
      ),
    );
  }
}
